---
- name: Download Helm
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/helm.sh
    mode: '770'

- name: Install Helm
  shell: /tmp/helm.sh

- name: Setup Helm Repos
  shell: |
    helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
    helm repo add jetstack https://charts.jetstack.io
    kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.crds.yaml
    helm upgrade -i cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace
    helm upgrade -i rancher rancher-latest/rancher --create-namespace --namespace cattle-system --set hostname=rancher.sdc.cpp --set bootstrapPassword=password --set replicas=1
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
